docs: command to persist database
lichess-org/lila-docker pull request #41
Opened 2023-12-06 21:59 UTC by Juesto

more details/as requested in #36

2023-12-08 23:12 UTC, fitztrev requested changes
After this command is run, what's the process to have the mongodb container use this volume on future starts?

2023-12-08 23:12 UTC, fitztrev commented on README.md
> +docker cp lila-docker-mongodb-1:/data/db ./database
Can `docker compose cp` be used here instead?

2023-12-08 23:12 UTC, fitztrev commented on README.md
> +docker cp lila-docker-mongodb-1:/data/db ./database
If this command gets added to the docs, I think we should also add the `database` folder to be gitignored out-of-the-box.

2023-12-09 04:34 UTC, Juesto commented on README.md
> +docker cp lila-docker-mongodb-1:/data/db ./database
perhaps?

2023-12-09 04:34 UTC, Juesto commented
> After this command is run, what's the process to have the mongodb container use this volume on future starts?

docker automatically adds the volume to docker-compose.yml when it executes the copy, i think. not sure

2023-12-09 14:25 UTC, fitztrev commented
> > After this command is run, what's the process to have the mongodb container use this volume on future starts?
> 
> docker automatically adds the volume to docker-compose.yml when it executes the copy, i think. not sure

Can you test this and the `docker compose cp` and report back?

2023-12-10 16:18 UTC, Juesto commented on README.md
> +docker cp lila-docker-mongodb-1:/data/db ./database
yes

2023-12-10 16:20 UTC, Juesto commented
> > > After this command is run, what's the process to have the mongodb container use this volume on future starts?
> > 
> > 
> > docker automatically adds the volume to docker-compose.yml when it executes the copy, i think. not sure
> 
> Can you test this and the `docker compose cp` and report back?

see commit, maybe i should be less vague about it

2023-12-10 19:25 UTC, merged